# This is a generated file. Not intended for manual editing.
services:
  basetemplatepoc:
    build:
      context: "F:\\BaseTemplate\\base-template-poc\\BaseTemplatePoc"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57407"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "basetemplatepoc:dev"
    ports:
    - "127.0.0.1:57007:57000"
    - "127.0.0.1:57207:57200"
    - "127.0.0.1:57407:57407"
    volumes:
    - "F:\\BaseTemplate\\base-template-poc\\BaseTemplatePoc:/app:rw"
    - "F:\\BaseTemplate\\base-template-poc\\BaseTemplatePoc:/src:rw"
    - "C:\\Users\\Outsider\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Outsider\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.3.0.3\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2025.3.0.1\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Outsider\\AppData\\Local\\JetBrains\\Rider2025.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_12_02_11_30_07:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
